public enum CardCodename
{
    UNKNOWN,
    DEFAULT_HOMEWORLD,
    FRIGATE,
    CRUISER,
    BATTLESHIP,
    SMALL_SHIPYARD,
    SHIPYARD,
    SHORT_TERM_INVESTMENT,
    LONG_TERM_INVESTMENT,
    EFFICIENCY_DRIVE
}
