public enum GameState
{
    AWAITING_CHALLENGER,
    SETUP,
    UPKEEP,
    LOGISTICS_PLANNING,
    LOGISTICS_RESOLUTION,
    COMBAT_PLANNING,
    LASER_WEAPON_RESOLUTION,
    POINT_DEFENCE_PLANNING,
    POINT_DEFENCE_RESOLUTION,
    BOMBARDMENT, 
    WAITING_FOR_OPPONENT
}

