public enum GamePhase
{
    AWAITING_CHALLENGER,
    SETUP,
    UPKEEP,
    LOGISTICS_PLANNING,
    LOGISTICS_RESOLUTION,
    COMBAT_PLANNING,
    LASER_WEAPON_RESOLUTION,
    POINT_DEFENCE_PLANNING,
    POINT_DEFENCE_RESOLUTION,
    BOMBARDMENT
}

